import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import bcrypt from "bcryptjs";
import postgres from "postgres";

function buildConnectionStringFromParts() {
  const host =
    process.env.POSTGRES_HOST ||
    process.env.PGHOST ||
    process.env.PGHOST_UNPOOLED;
  const database = process.env.POSTGRES_DATABASE || process.env.PGDATABASE;
  const user = process.env.POSTGRES_USER || process.env.PGUSER;
  const password = process.env.POSTGRES_PASSWORD || process.env.PGPASSWORD;

  if (!host || !database || !user || !password) {
    return null;
  }

  return `postgresql://${encodeURIComponent(user)}:${encodeURIComponent(password)}@${host}/${database}`;
}

const connectionString =
  process.env.POSTGRES_PRISMA_URL ||
  process.env.POSTGRES_URL ||
  process.env.DATABASE_URL ||
  process.env.POSTGRES_URL_NON_POOLING ||
  process.env.DATABASE_URL_UNPOOLED ||
  process.env.POSTGRES_URL_NO_SSL ||
  buildConnectionStringFromParts();

if (!connectionString) {
  throw new Error(
    "Missing database connection string. Set POSTGRES_PRISMA_URL, POSTGRES_URL, DATABASE_URL, POSTGRES_URL_NON_POOLING, DATABASE_URL_UNPOOLED, or the POSTGRES_/PG* parts."
  );
}

const sql = postgres(connectionString, {
  max: 1,
  connect_timeout: Number(process.env.POSTGRES_CONNECT_TIMEOUT || "10"),
  idle_timeout: Number(process.env.POSTGRES_IDLE_TIMEOUT || "20"),
  max_lifetime: Number(process.env.POSTGRES_MAX_LIFETIME || "300"),
  prepare: false,
  ssl: /localhost|127\.0\.0\.1/i.test(connectionString) ? undefined : "require",
});

const curriculumPath = resolve(process.cwd(), "setswana.json");
const curriculum = JSON.parse(await readFile(curriculumPath, "utf8"));

const quests = [
  {
    title: "Day 1",
    description: "Start your journey by maintaining a 1-day streak.",
    required_streak: 1,
    points: 10,
  },
  {
    title: "Day 3",
    description: "Reach a 3-day streak.",
    required_streak: 3,
    points: 30,
  },
  {
    title: "Day 7",
    description: "Reach a 7-day streak.",
    required_streak: 7,
    points: 100,
  },
  {
    title: "Day 30",
    description: "Reach a 1-month streak.",
    required_streak: 30,
    points: 1000,
  },
];

async function ensureSchema() {
  await sql`
    create table if not exists users (
      id integer generated by default as identity primary key,
      email varchar not null unique,
      full_name varchar,
      hashed_password varchar,
      is_active boolean default true,
      is_admin boolean default false,
      firebase_id varchar unique,
      image_src varchar,
      hearts integer default 5,
      points integer default 0,
      xp integer default 0,
      streak_count integer default 0,
      last_activity_date date,
      longest_streak integer default 0,
      streak_frozen boolean default false,
      created_at timestamptz default now(),
      updated_at timestamptz default now()
    )
  `;

  await sql`
    create table if not exists courses (
      id integer generated by default as identity primary key,
      title varchar not null,
      description text,
      image_src varchar,
      order_index integer default 0
    )
  `;

  await sql`
    create table if not exists units (
      id integer generated by default as identity primary key,
      title varchar not null,
      description text,
      course_id integer not null references courses(id) on delete cascade,
      order_index integer default 0
    )
  `;

  await sql`
    create table if not exists lessons (
      id integer generated by default as identity primary key,
      title varchar not null,
      unit_id integer not null references units(id) on delete cascade,
      order_index integer default 0
    )
  `;

  await sql`
    create table if not exists challenges (
      id integer generated by default as identity primary key,
      lesson_id integer not null references lessons(id) on delete cascade,
      type varchar not null,
      question text not null,
      correct_text text,
      audio_src varchar,
      order_index integer default 0
    )
  `;

  await sql`
    create table if not exists challenge_options (
      id integer generated by default as identity primary key,
      challenge_id integer not null references challenges(id) on delete cascade,
      text varchar not null,
      correct boolean default false,
      image_src varchar,
      audio_src varchar
    )
  `;

  await sql`
    create table if not exists quests (
      id integer generated by default as identity primary key,
      title varchar not null,
      description text not null,
      points integer default 0,
      required_streak integer not null
    )
  `;

  await sql`
    create table if not exists user_quests (
      id integer generated by default as identity primary key,
      user_id integer not null references users(id) on delete cascade,
      quest_id integer not null references quests(id) on delete cascade,
      completed boolean default false,
      completion_date timestamptz
    )
  `;

  await sql`
    create table if not exists user_progress (
      id integer generated by default as identity primary key,
      user_id integer not null references users(id) on delete cascade,
      lesson_id integer not null references lessons(id) on delete cascade,
      completed boolean default false,
      hearts_used integer default 0,
      points_earned integer default 0,
      created_at timestamptz default now(),
      updated_at timestamptz default now()
    )
  `;
}

async function ensureAdminUser() {
  const adminEmail = process.env.ADMIN_EMAIL || "admin@puolingo.com";
  const adminPassword = process.env.ADMIN_PASSWORD || "admin123";
  const fullName = process.env.ADMIN_FULL_NAME || "Admin User";
  const hashedPassword = await bcrypt.hash(adminPassword, 10);

  await sql`
    insert into users (
      email,
      full_name,
      hashed_password,
      is_active,
      is_admin,
      hearts,
      points,
      xp,
      streak_count,
      longest_streak,
      streak_frozen
    )
    values (
      ${adminEmail},
      ${fullName},
      ${hashedPassword},
      true,
      true,
      5,
      0,
      0,
      0,
      0,
      false
    )
    on conflict (email) do update set
      full_name = excluded.full_name,
      hashed_password = excluded.hashed_password,
      is_active = true,
      is_admin = true,
      updated_at = now()
  `;

  console.log(`Admin user ready: ${adminEmail}`);
}

async function upsertCourse(courseData, index) {
  const [course] = await sql`
    insert into courses (title, description, image_src, order_index)
    values (
      ${courseData.title},
      ${courseData.description ?? null},
      ${courseData.image_src ?? null},
      ${courseData.order_index ?? index}
    )
    on conflict do nothing
    returning id
  `;

  if (course) {
    return course.id;
  }

  const [existing] = await sql`
    select id
    from courses
    where title = ${courseData.title}
    limit 1
  `;

  await sql`
    update courses
    set
      description = ${courseData.description ?? null},
      image_src = ${courseData.image_src ?? null},
      order_index = ${courseData.order_index ?? index}
    where id = ${existing.id}
  `;

  return existing.id;
}

async function upsertUnit(courseId, unitData) {
  const [existing] = await sql`
    select id
    from units
    where course_id = ${courseId} and title = ${unitData.title}
    limit 1
  `;

  if (existing) {
    await sql`
      update units
      set
        description = ${unitData.description ?? null},
        order_index = ${unitData.order_index ?? 0}
      where id = ${existing.id}
    `;
    return existing.id;
  }

  const [unit] = await sql`
    insert into units (title, description, course_id, order_index)
    values (
      ${unitData.title},
      ${unitData.description ?? null},
      ${courseId},
      ${unitData.order_index ?? 0}
    )
    returning id
  `;

  return unit.id;
}

async function upsertLesson(unitId, lessonData) {
  const [existing] = await sql`
    select id
    from lessons
    where unit_id = ${unitId} and title = ${lessonData.title}
    limit 1
  `;

  if (existing) {
    await sql`
      update lessons
      set order_index = ${lessonData.order_index ?? 0}
      where id = ${existing.id}
    `;
    return existing.id;
  }

  const [lesson] = await sql`
    insert into lessons (title, unit_id, order_index)
    values (${lessonData.title}, ${unitId}, ${lessonData.order_index ?? 0})
    returning id
  `;

  return lesson.id;
}

async function upsertChallenge(lessonId, challengeData) {
  const [existing] = await sql`
    select id
    from challenges
    where lesson_id = ${lessonId} and question = ${challengeData.question}
    limit 1
  `;

  if (existing) {
    await sql`
      update challenges
      set
        type = ${challengeData.type},
        correct_text = ${challengeData.correct_text ?? null},
        audio_src = ${challengeData.audio_src ?? null},
        order_index = ${challengeData.order_index ?? 0}
      where id = ${existing.id}
    `;
    return existing.id;
  }

  const [challenge] = await sql`
    insert into challenges (lesson_id, type, question, correct_text, audio_src, order_index)
    values (
      ${lessonId},
      ${challengeData.type},
      ${challengeData.question},
      ${challengeData.correct_text ?? null},
      ${challengeData.audio_src ?? null},
      ${challengeData.order_index ?? 0}
    )
    returning id
  `;

  return challenge.id;
}

async function replaceOptions(challengeId, options) {
  await sql`delete from challenge_options where challenge_id = ${challengeId}`;

  for (const option of options || []) {
    await sql`
      insert into challenge_options (challenge_id, text, correct, image_src, audio_src)
      values (
        ${challengeId},
        ${option.text},
        ${Boolean(option.correct)},
        ${option.image_src ?? null},
        ${option.audio_src ?? null}
      )
    `;
  }
}

async function seedCurriculum() {
  const courses = [
    {
      title: curriculum.course.title,
      description: curriculum.course.description,
      image_src: curriculum.course.image_src,
      order_index: 1,
      units: curriculum.units ?? [],
    },
  ];

  for (const [courseIndex, courseData] of courses.entries()) {
    const courseId = await upsertCourse(courseData, courseIndex + 1);

    for (const unitData of courseData.units) {
      const unitId = await upsertUnit(courseId, unitData);

      for (const lessonData of unitData.lessons ?? []) {
        const lessonId = await upsertLesson(unitId, lessonData);

        for (const challengeData of lessonData.challenges ?? []) {
          const challengeId = await upsertChallenge(lessonId, challengeData);
          await replaceOptions(challengeId, challengeData.options ?? []);
        }
      }
    }
  }
}

async function seedQuests() {
  for (const quest of quests) {
    const [existing] = await sql`
      select id
      from quests
      where title = ${quest.title}
      limit 1
    `;

    if (existing) {
      await sql`
        update quests
        set
          description = ${quest.description},
          points = ${quest.points},
          required_streak = ${quest.required_streak}
        where id = ${existing.id}
      `;
    } else {
      await sql`
        insert into quests (title, description, points, required_streak)
        values (${quest.title}, ${quest.description}, ${quest.points}, ${quest.required_streak})
      `;
    }
  }
}

try {
  console.log("Ensuring schema...");
  await ensureSchema();
  console.log("Ensuring admin user...");
  await ensureAdminUser();
  console.log("Seeding curriculum...");
  await seedCurriculum();
  console.log("Seeding quests...");
  await seedQuests();
  console.log("Bootstrap complete.");
} finally {
  await sql.end();
}
