"""initial_migration

Revision ID: fc1837157989
Revises: 
Create Date: 2026-01-29 18:09:28.483707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1837157989'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('firebase_id', sa.String(), nullable=True),
        sa.Column('image_src', sa.String(), nullable=True),
        sa.Column('hearts', sa.Integer(), nullable=True),
        sa.Column('points', sa.Integer(), nullable=True),
        sa.Column('xp', sa.Integer(), nullable=True),
        sa.Column('streak_count', sa.Integer(), nullable=True),
        sa.Column('last_activity_date', sa.Date(), nullable=True),
        sa.Column('longest_streak', sa.Integer(), nullable=True),
        sa.Column('streak_frozen', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.UniqueConstraint('email', name='users_email_key'),
        sa.UniqueConstraint('firebase_id', name='users_firebase_id_key')
    )

    op.create_table(
        'courses',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('image_src', sa.String(), nullable=True),
        sa.Column('order_index', sa.Integer(), nullable=True)
    )

    op.create_table(
        'units',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('course_id', sa.Integer(), sa.ForeignKey('courses.id'), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=True)
    )

    op.create_table(
        'lessons',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('unit_id', sa.Integer(), sa.ForeignKey('units.id'), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=True)
    )

    op.create_table(
        'challenges',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('lesson_id', sa.Integer(), sa.ForeignKey('lessons.id'), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('correct_text', sa.Text(), nullable=True),
        sa.Column('audio_src', sa.String(), nullable=True),
        sa.Column('order_index', sa.Integer(), nullable=True)
    )

    op.create_table(
        'challenge_options',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('challenge_id', sa.Integer(), sa.ForeignKey('challenges.id'), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('correct', sa.Boolean(), nullable=True),
        sa.Column('image_src', sa.String(), nullable=True),
        sa.Column('audio_src', sa.String(), nullable=True)
    )

    op.create_table(
        'quests',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('points', sa.Integer(), nullable=True),
        sa.Column('required_streak', sa.Integer(), nullable=False)
    )

    op.create_table(
        'user_quests',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('quest_id', sa.Integer(), sa.ForeignKey('quests.id'), nullable=False),
        sa.Column('completed', sa.Boolean(), nullable=True),
        sa.Column('completion_date', sa.DateTime(), nullable=True)
    )

    op.create_table(
        'user_progress',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('lesson_id', sa.Integer(), sa.ForeignKey('lessons.id'), nullable=False),
        sa.Column('completed', sa.Boolean(), nullable=True),
        sa.Column('hearts_used', sa.Integer(), nullable=True),
        sa.Column('points_earned', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    op.drop_table('user_quests')
    op.drop_table('quests')
    op.drop_table('challenge_options')
    op.drop_table('challenges')
    op.drop_table('lessons')
    op.drop_table('units')
    op.drop_table('courses')
    op.drop_table('users')
    # ### end Alembic commands ###
