"""initial_migration

Revision ID: fc1837157989
Revises: 
Create Date: 2026-01-29 18:09:28.483707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1837157989'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_id', sa.String(), nullable=True))
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['firebase_id'])
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    op.drop_column('users', 'firebase_id')
    # ### end Alembic commands ###
