import postgres from "postgres";
let cachedSql: postgres.Sql | null = null;
let schemaInitPromise: Promise<void> | null = null;
let schemaVerified = false;

export function getSql() {
  if (cachedSql) {
    return cachedSql;
  }

  const connectionString =
    process.env.POSTGRES_URL ||
    process.env.POSTGRES_PRISMA_URL ||
    process.env.POSTGRES_URL_NON_POOLING ||
    process.env.DATABASE_URL;

  if (!connectionString) {
    throw new Error(
      "Missing database connection string. Set POSTGRES_URL, POSTGRES_PRISMA_URL, POSTGRES_URL_NON_POOLING, or DATABASE_URL."
    );
  }

  const useSsl = !/localhost|127\.0\.0\.1/i.test(connectionString);
  cachedSql = postgres(connectionString, {
    max: Number(process.env.POSTGRES_POOL_MAX || "5"),
    ssl: useSsl ? "require" : undefined,
    prepare: false,
    onnotice: () => {},
  });

  return cachedSql;
}

export function getAuthConfig() {
  const secretKey = process.env.SECRET_KEY;
  if (!secretKey) {
    throw new Error("Missing required environment variable: SECRET_KEY");
  }

  return {
    secretKey,
    accessTokenExpireMinutes: Number(process.env.ACCESS_TOKEN_EXPIRE_MINUTES || "30"),
    refreshTokenExpireDays: Number(process.env.REFRESH_TOKEN_EXPIRE_DAYS || "7"),
  };
}

async function createSchema() {
  await sql`
    create table if not exists users (
      id integer generated by default as identity primary key,
      email varchar not null unique,
      full_name varchar,
      hashed_password varchar,
      is_active boolean default true,
      is_admin boolean default false,
      firebase_id varchar unique,
      image_src varchar,
      hearts integer default 5,
      points integer default 0,
      xp integer default 0,
      streak_count integer default 0,
      last_activity_date date,
      longest_streak integer default 0,
      streak_frozen boolean default false,
      created_at timestamptz default now(),
      updated_at timestamptz default now()
    )
  `;

  await sql`
    create table if not exists courses (
      id integer generated by default as identity primary key,
      title varchar not null,
      description text,
      image_src varchar,
      order_index integer default 0
    )
  `;

  await sql`
    create table if not exists units (
      id integer generated by default as identity primary key,
      title varchar not null,
      description text,
      course_id integer not null references courses(id) on delete cascade,
      order_index integer default 0
    )
  `;

  await sql`
    create table if not exists lessons (
      id integer generated by default as identity primary key,
      title varchar not null,
      unit_id integer not null references units(id) on delete cascade,
      order_index integer default 0
    )
  `;

  await sql`
    create table if not exists challenges (
      id integer generated by default as identity primary key,
      lesson_id integer not null references lessons(id) on delete cascade,
      type varchar not null,
      question text not null,
      correct_text text,
      audio_src varchar,
      order_index integer default 0
    )
  `;

  await sql`
    create table if not exists challenge_options (
      id integer generated by default as identity primary key,
      challenge_id integer not null references challenges(id) on delete cascade,
      text varchar not null,
      correct boolean default false,
      image_src varchar,
      audio_src varchar
    )
  `;

  await sql`
    create table if not exists quests (
      id integer generated by default as identity primary key,
      title varchar not null,
      description text not null,
      points integer default 0,
      required_streak integer not null
    )
  `;

  await sql`
    create table if not exists user_quests (
      id integer generated by default as identity primary key,
      user_id integer not null references users(id) on delete cascade,
      quest_id integer not null references quests(id) on delete cascade,
      completed boolean default false,
      completion_date timestamptz
    )
  `;

  await sql`
    create table if not exists user_progress (
      id integer generated by default as identity primary key,
      user_id integer not null references users(id) on delete cascade,
      lesson_id integer not null references lessons(id) on delete cascade,
      completed boolean default false,
      hearts_used integer default 0,
      points_earned integer default 0,
      created_at timestamptz default now(),
      updated_at timestamptz default now()
    )
  `;
}

export async function ensureAppSchema() {
  if (schemaVerified) {
    return;
  }

  if (!schemaInitPromise) {
    schemaInitPromise = (async () => {
      const result = await sql`
        select to_regclass('public.users') as users_table
      `;

      if (result[0]?.users_table) {
        schemaVerified = true;
        return;
      }

      await createSchema();
      schemaVerified = true;
    })().catch((error) => {
      schemaInitPromise = null;
      throw error;
    });
  }

  await schemaInitPromise;
}

export function sql(
  strings: TemplateStringsArray,
  ...values: unknown[]
) {
  // The postgres tag function is lazily resolved so build-time env checks do not fail.
  // We keep this wrapper narrow and cast once here rather than duplicating the workaround at each query call.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (getSql() as any)(strings, ...values);
}
